# https://golangci-lint.run/usage/configuration/
linters:
  enable-all: false
  presets:
    - bugs
    - complexity
    - format
    - import
    - module
    - sql
    # - unused # Deactivated because of false positives for mocks
    - comment
    #- error
    #- performance
    #- style
    #- test
    #- metalinter
  disable:
    - gofumpt # "gofmt" is OK for us, no need for stricter rules (https://github.com/mvdan/gofumpt)
    - gci # No need to explicitly format imports using GCI (https://github.com/daixiang0/gci)
    - depguard # No need to restrict imported packages (https://github.com/OpenPeeDeeP/depguard)
run:
  tests: false
  skip-dirs:
    - node_modules
