version: "2"
run:
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - gomodguard
    - gosec
    - gosmopolitan
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unparam
    - usetesting
    - zerologlint
  disable:
    - depguard
    - err113
    - paralleltest
    - revive
    - testpackage
    - wrapcheck
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - node_modules
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
    paths:
      - node_modules
      - third_party$
      - builtin$
      - examples$
