# https://golangci-lint.run/usage/configuration/
linters:
  enable-all: false
  presets:
    - bugs
    - complexity
    - format
    - import
    - module
    - sql
    - comment
    - performance
    - test
    - error
    - unused
    #- style
    #- metalinter
  disable:
    - gofumpt # "gofmt" is OK for us, no need for stricter rules (https://github.com/mvdan/gofumpt)
    - gci # No need to explicitly format imports using GCI (https://github.com/daixiang0/gci)
    - depguard # No need to restrict imported packages (https://github.com/OpenPeeDeeP/depguard)
    - goerr113 # Using static errors is not necessary (https://github.com/Djarvur/go-err113)
    - wrapcheck # Wrapping errors is not necessary (https://github.com/tomarrell/wrapcheck#tldr)
run:
  tests: false
  skip-dirs:
    - node_modules
