sources:
  - type: golang
    path: go.mod
version: 0.1.0
linkReplacements:
  - "https://github.com/exasol/exasol-test-setup-abstraction-server/blob/397987f03514/go-client/LICENSE|https://github.com/exasol/exasol-test-setup-abstraction-server/blob/main/LICENSE"