sources:
  - type: golang
    path: go.mod
  - type: maven
    path: extension-manager-integration-test-java/pom.xml
    modules:
      - maven_central
version: 0.1.0
linkReplacements:
  - "https://github.com/exasol/exasol-test-setup-abstraction-server/blob/go-client/v0.2.3/go-client/LICENSE|https://github.com/exasol/exasol-test-setup-abstraction-server/blob/main/LICENSE"
  - "Unknown|https://github.com/DATA-DOG/go-sqlmock/blob/master/LICENSE"
excludes:
