sources:
  - type: golang
    path: go.mod
  - type: maven
    path: extension-manager-client-java/pom.xml
    modules:
      - maven_central
    parentPom:
      groupId: "com.exasol"
      artifactId: "extension-manager-parent-pom"
      version: "${revision}"
      relativePath: "../pom.xml"
  - type: maven
    path: extension-manager-integration-test-java/pom.xml
    modules:
      - integration_tests
      - maven_central
    parentPom:
      groupId: "com.exasol"
      artifactId: "extension-manager-parent-pom"
      version: "${revision}"
      relativePath: "../pom.xml"
  - type: npm
    path: registry/package.json
  - type: npm
    path: registry-upload/package.json
  - type: npm
    path: pkg/parameterValidator/package.json
version: 0.5.10
linkReplacements:
  - "Unknown|https://github.com/DATA-DOG/go-sqlmock/blob/master/LICENSE"
  - "https://github.com/swagger-api/swagger-core/modules/swagger-annotations|https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-annotations"
  - "jquery.org/license|https://jquery.org/license/"
  - "https://github.com/swagger-api/swagger-codegen/modules/swagger-codegen-maven-plugin|https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin"
excludes:
  # We use the PK shell script instead of the Maven plugin
  - regex: "W-PK-CORE-151: Pom file '.*/pom.xml' contains no reference to project-keeper-maven-plugin."
  # We use release-droid until PK supports Go projects
  - "E-PK-CORE-26: '.github/workflows/release_droid_prepare_original_checksum.yml' exists but must not exist. Reason: Release-droid workflows are replaced by release.yml"
  - "E-PK-CORE-26: '.github/workflows/release_droid_print_quick_checksum.yml' exists but must not exist. Reason: Release-droid workflows are replaced by release.yml"
  - "E-PK-CORE-26: '.github/workflows/release_droid_upload_github_release_assets.yml' exists but must not exist. Reason: Release-droid workflows are replaced by release.yml"
  - "E-PK-CORE-26: '.github/workflows/release_droid_release_on_maven_central.yml' exists but must not exist. Reason: Release-droid workflows are replaced by release.yml"
