package restAPI

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"sync"

	cont "github.com/exasol/extension-manager/extensionController"

	"github.com/exasol/exasol-driver-go"
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// docs are generated by Swag CLI, you have to import it.
	_ "github.com/exasol/extension-manager/generatedApiDocs"
)

// RestAPI is the interface that provides the REST API server of the extension-manager.
type RestAPI interface {
	// Serve starts the server. This method blocks until the server is stopped or fails.
	Serve()
	// Stop stops the server
	Stop()
}

// @title           Exasol extension manager REST API
// @version         0.1.0
// @description     This is a REST API for managing extensions in an Exasol database.

// @contact.name   Exasol Integration team
// @contact.email  opensource@exasol.com

// @license.name  MIT
// @license.url   https://github.com/exasol/extension-manager/blob/main/LICENSE

// @BasePath  /
// @accept json
// @produce json

// Create creates a new RestAPI.
func Create(controller cont.ExtensionController, serverAddress string) RestAPI {
	return &restAPIImpl{controller: controller, serverAddress: serverAddress}
}

type restAPIImpl struct {
	controller    cont.ExtensionController
	serverAddress string
	server        *http.Server
	stopped       *bool
	stoppedMutex  *sync.Mutex
}

func (api *restAPIImpl) Serve() {
	if api.server != nil {
		panic("server already running")
	}
	api.setStopped(false)
	router := gin.Default()
	router.GET("/extensions", api.handleGetExtensions)
	router.GET("/installations", api.handleGetInstallations)
	router.PUT("/installations", api.handlePutInstallation)
	router.PUT("/instances", api.handlePutInstance)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	srv := &http.Server{
		Addr:    api.serverAddress,
		Handler: router,
	}
	api.server = srv
	log.Printf("Starting server on %s...\n", api.serverAddress)
	err := api.server.ListenAndServe() // blocking
	if err != nil && !api.isStopped() {
		panic(fmt.Sprintf("failed to start rest API server. Cause: %v", err))
	}
}

func (api *restAPIImpl) setStopped(stopped bool) {
	if api.stopped == nil {
		stopped := false
		api.stopped = &stopped
		api.stoppedMutex = &sync.Mutex{}
	}
	api.stoppedMutex.Lock()
	defer api.stoppedMutex.Unlock()
	*api.stopped = stopped
}

func (api *restAPIImpl) isStopped() bool {
	api.stoppedMutex.Lock()
	defer api.stoppedMutex.Unlock()
	return *api.stopped
}

func (api *restAPIImpl) Stop() {
	if api.server == nil {
		panic("cant stop server since it's not running")
	}
	api.setStopped(true)
	err := api.server.Shutdown(context.Background())
	if err != nil {
		panic(fmt.Sprintf("failed to shutdown rest API server. Cause: %v", err))
	}
	api.server = nil
}

// @Summary      Get all extensions
// @Description  Get a list of all available extensions.
// @Id           getExtensions
// @Produce      json
// @Success      200 {object} ExtensionsResponse
// @Param        dbHost query string true "Hostname of the Exasol DB to manage"
// @Param        dbPort query int true "Port number of the Exasol DB to manage"
// @Param        dbUser query string true "Username of the Exasol DB to manage"
// @Param        dbPass query string true "Password of the Exasol DB to manage"
// @Failure      500 {object} string
// @Router       /extensions [get]
func (api *restAPIImpl) handleGetExtensions(c *gin.Context) {
	response, err := api.getExtensions(c)
	api.sendResponse(c, response, err)
}

func (api *restAPIImpl) getExtensions(c *gin.Context) (*ExtensionsResponse, error) {
	db, err := api.openDBConnection(c)
	if err != nil {
		return nil, err
	}
	defer closeDbConnection(db)
	extensions, err := api.controller.GetAllExtensions(db)
	if err != nil {
		return nil, err
	}
	convertedExtensions := make([]ExtensionsResponseExtension, 0, len(extensions))
	for _, extension := range extensions {
		ext := ExtensionsResponseExtension{Id: extension.Id, Name: extension.Name, Description: extension.Description, InstallableVersions: extension.InstallableVersions}
		convertedExtensions = append(convertedExtensions, ext)
	}
	response := ExtensionsResponse{
		Extensions: convertedExtensions,
	}
	return &response, nil
}

// @Description Response containing all available extensions
type ExtensionsResponse struct {
	Extensions []ExtensionsResponseExtension `json:"extensions"` // All available extensions.
}

// @Description Extension information
type ExtensionsResponseExtension struct {
	Id                  string   `json:"id"`                  // ID of the extension. Don't store this as it may change in the future.
	Name                string   `json:"name"`                // The name of the extension to be displayed to the user.
	Description         string   `json:"description"`         // The description of the extension to be displayed to the user.
	InstallableVersions []string `json:"installableVersions"` // A list of versions of this extension available for installation.
}

// @Summary      Get all installations.
// @Description  Get a list of all installations. Installation means, that an extension is installed in the database (e.g. JAR files added to BucketFS, Adapter Script created).
// @Id           getInstallations
// @Produce      json
// @Success      200 {object} InstallationsResponse
// @Param        dbHost query string true "Hostname of the Exasol DB to manage"
// @Param        dbPort query int true "Port number of the Exasol DB to manage"
// @Param        dbUser query string true "Username of the Exasol DB to manage"
// @Param        dbPass query string true "Password of the Exasol DB to manage"
// @Failure      500 {object} string
// @Router       /installations [get]
func (api *restAPIImpl) handleGetInstallations(c *gin.Context) {
	response, err := api.getInstallations(c)
	api.sendResponse(c, response, err)
}

func (api *restAPIImpl) getInstallations(c *gin.Context) (*InstallationsResponse, error) {
	db, err := api.openDBConnection(c)
	if err != nil {
		return nil, err
	}
	defer closeDbConnection(db)
	installations, err := api.controller.GetAllInstallations(db)
	if err != nil {
		return nil, err
	}
	convertedInstallations := make([]InstallationsResponseInstallation, 0, len(installations))
	for _, installation := range installations {
		convertedInstallations = append(convertedInstallations, InstallationsResponseInstallation{installation.Name, installation.Version, installation.InstanceParameters})
	}
	response := InstallationsResponse{
		Installations: convertedInstallations,
	}
	return &response, nil
}

// @Summary      Install an extension.
// @Description  This installs an extension in a given version.
// @Id           installExtension
// @Produce      json
// @Success      200 {object} string
// @Param        dbHost query string true "Hostname of the Exasol DB to manage"
// @Param        dbPort query int true "Port number of the Exasol DB to manage"
// @Param        dbUser query string true "Username of the Exasol DB to manage"
// @Param        dbPass query string true "Password of the Exasol DB to manage"
// @Param        extensionId query string true "ID of the extension to install"
// @Param        extensionVersion query string true "Version of the extension to install"
// @Param        dummy body string false "dummy body" default()
// @Failure      500 {object} string
// @Router       /installations [put]
func (api *restAPIImpl) handlePutInstallation(c *gin.Context) {
	result, err := api.installExtension(c)
	api.sendResponse(c, result, err)
}

func (api *restAPIImpl) installExtension(c *gin.Context) (string, error) {
	db, err := api.openDBConnection(c)
	if err != nil {
		return "", err
	}
	defer closeDbConnection(db)
	query := c.Request.URL.Query()
	extensionId := query.Get("extensionId")
	if extensionId == "" {
		return "", fmt.Errorf("missing parameter extensionId")
	}
	extensionVersion := query.Get("extensionVersion")
	if extensionVersion == "" {
		return "", fmt.Errorf("missing parameter extensionVersion")
	}

	err = api.controller.InstallExtension(db, extensionId, extensionVersion)

	if err != nil {
		return "", fmt.Errorf("error installing extension: %v", err)
	}
	return "", nil
}

// @Summary      Create an instance of an extension.
// @Description  This creates an instance of an extension, e.g. a virtual schema.
// @Id           createInstance
// @Produce      json
// @Success      200 {object} CreateInstanceResponse
// @Param        dbHost query string true "Hostname of the Exasol DB to manage"
// @Param        dbPort query int true "Port number of the Exasol DB to manage"
// @Param        dbUser query string true "Username of the Exasol DB to manage"
// @Param        dbPass query string true "Password of the Exasol DB to manage"
// @Param        createInstanceRequest body CreateInstanceRequest true "Request data for creating an instance"
// @Failure      500 {object} string
// @Router       /instances [put]
func (api *restAPIImpl) handlePutInstance(c *gin.Context) {
	result, err := api.createInstance(c)
	api.sendResponse(c, result, err)
}

func (api *restAPIImpl) createInstance(c *gin.Context) (CreateInstanceResponse, error) {
	db, err := api.openDBConnection(c)
	var response CreateInstanceResponse
	if err != nil {
		return response, err
	}
	defer closeDbConnection(db)
	var request CreateInstanceRequest
	if err := c.BindJSON(&request); err != nil {
		return response, fmt.Errorf("invalid request: %w", err)
	}

	var parameters []cont.ParameterValue
	for _, p := range request.ParameterValues {
		parameters = append(parameters, cont.ParameterValue{Name: p.Name, Value: p.Value})
	}
	response.InstanceName, err = api.controller.CreateInstance(db, request.ExtensionId, request.ExtensionVersion, parameters)
	if err != nil {
		return response, fmt.Errorf("error installing extension: %v", err)
	}
	return response, nil
}

// @Description Request data for creating a new instance of an extension.
type CreateInstanceRequest struct {
	ExtensionId      string           `json:"extensionId"`      // The ID of the extension
	ExtensionVersion string           `json:"extensionVersion"` // The version of the extension
	ParameterValues  []ParameterValue `json:"parameterValues"`  // The parameters for the new instance
}

// @Description Parameter values for creating a new instance.
type ParameterValue struct {
	Name  string `json:"name"`  // The name of the parameter
	Value string `json:"value"` // The value of the parameter
}

// @Description Response data for creating a new instance of an extension.
type CreateInstanceResponse struct {
	InstanceName string `json:"instanceName"` // The name of the newly created instance
}

func (api *restAPIImpl) sendResponse(c *gin.Context, response interface{}, err error) {
	if err != nil {
		c.String(500, fmt.Sprintf("Request failed: %s", err.Error()))
		log.Printf("Request failed: %v\n", err)
		return
	}
	if s, ok := response.(string); ok {
		c.String(200, s)
	} else {
		c.JSON(200, response)
	}
}

func closeDbConnection(db *sql.DB) {
	err := db.Close()
	if err != nil {
		// Strange but not critical. So we just log it and go on.
		fmt.Printf("failed to close db connection. Cause %v", err)
	}
}

func (api *restAPIImpl) openDBConnection(c *gin.Context) (*sql.DB, error) {
	config, err := getDbConfig(c)
	if err != nil {
		return nil, err
	}
	config.Autocommit(false).ValidateServerCertificate(false)
	database, err := sql.Open("exasol", config.String())
	if err != nil {
		return nil, fmt.Errorf("failed to open a database connection. Cause: %w", err)
	}
	return database, nil
}

func getDbConfig(c *gin.Context) (*exasol.DSNConfigBuilder, error) {
	query := c.Request.URL.Query()
	host := query.Get("dbHost")
	if host == "" {
		return nil, fmt.Errorf("missing parameter dbHost")
	}
	portString := query.Get("dbPort")
	if portString == "" {
		return nil, fmt.Errorf("missing parameter dbPort")
	}
	port, err := strconv.Atoi(portString)
	if err != nil {
		return nil, fmt.Errorf("invalid value %q for parameter dbPort", portString)
	}
	user := query.Get("dbUser")
	if user == "" {
		return nil, fmt.Errorf("missing parameter dbUser")
	}
	password := query.Get("dbPass")
	if password == "" {
		return nil, fmt.Errorf("missing parameter dbPass")
	}
	config := exasol.NewConfig(user, password).Port(port).Host(host)
	return config, nil
}

type InstallationsResponse struct {
	Installations []InstallationsResponseInstallation `json:"installations"`
}

type InstallationsResponseInstallation struct {
	Name               string        `json:"name"`
	Version            string        `json:"version"`
	InstanceParameters []interface{} `json:"instanceParameters"`
}
