// Package generatedApiDocs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package generatedApiDocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Exasol Integration team",
            "email": "opensource@exasol.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/exasol/extension-manager/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/extensions": {
            "get": {
                "description": "Get a list of all available extensions, i.e. extensions that can be installed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extension"
                ],
                "summary": "Get all extensions",
                "operationId": "getAvailableExtensions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hostname of the Exasol DB to manage",
                        "name": "dbHost",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Port number of the Exasol DB to manage",
                        "name": "dbPort",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username of the Exasol DB to manage",
                        "name": "dbUser",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Password of the Exasol DB to manage",
                        "name": "dbPassword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Access token of the Exasol DB to manage",
                        "name": "dbAccessToken",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token of the Exasol DB to manage",
                        "name": "dbRefreshToken",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restAPI.ExtensionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/installations": {
            "get": {
                "description": "Get a list of all installed extensions. Installation means, that an extension is installed in the database (e.g. JAR files added to BucketFS and Adapter Script created).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extension"
                ],
                "summary": "Get all installed extensions.",
                "operationId": "getInstalledExtensions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hostname of the Exasol DB to manage",
                        "name": "dbHost",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Port number of the Exasol DB to manage",
                        "name": "dbPort",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username of the Exasol DB to manage",
                        "name": "dbUser",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Password of the Exasol DB to manage",
                        "name": "dbPassword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Access token of the Exasol DB to manage",
                        "name": "dbAccessToken",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token of the Exasol DB to manage",
                        "name": "dbRefreshToken",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restAPI.InstallationsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "This installs an extension in a given version, e.g. by creating Adapter Scripts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extension"
                ],
                "summary": "Install an extension.",
                "operationId": "installExtension",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hostname of the Exasol DB to manage",
                        "name": "dbHost",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Port number of the Exasol DB to manage",
                        "name": "dbPort",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username of the Exasol DB to manage",
                        "name": "dbUser",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Password of the Exasol DB to manage",
                        "name": "dbPassword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Access token of the Exasol DB to manage",
                        "name": "dbAccessToken",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token of the Exasol DB to manage",
                        "name": "dbRefreshToken",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID of the extension to install",
                        "name": "extensionId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version of the extension to install",
                        "name": "extensionVersion",
                        "in": "query",
                        "required": true
                    },
                    {
                        "default": "",
                        "description": "dummy body",
                        "name": "dummy",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/instances": {
            "put": {
                "description": "This creates a new instance of an extension, e.g. a virtual schema.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instance"
                ],
                "summary": "Create an instance of an extension.",
                "operationId": "createInstance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hostname of the Exasol DB to manage",
                        "name": "dbHost",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Port number of the Exasol DB to manage",
                        "name": "dbPort",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username of the Exasol DB to manage",
                        "name": "dbUser",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Password of the Exasol DB to manage",
                        "name": "dbPassword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Access token of the Exasol DB to manage",
                        "name": "dbAccessToken",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token of the Exasol DB to manage",
                        "name": "dbRefreshToken",
                        "in": "query"
                    },
                    {
                        "description": "Request data for creating an instance",
                        "name": "createInstanceRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restAPI.CreateInstanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restAPI.CreateInstanceResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "restAPI.CreateInstanceRequest": {
            "description": "Request data for creating a new instance of an extension.",
            "type": "object",
            "properties": {
                "extensionId": {
                    "description": "The ID of the extension",
                    "type": "string"
                },
                "extensionVersion": {
                    "description": "The version of the extension",
                    "type": "string"
                },
                "parameterValues": {
                    "description": "The parameters for the new instance",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restAPI.ParameterValue"
                    }
                }
            }
        },
        "restAPI.CreateInstanceResponse": {
            "description": "Response data for creating a new instance of an extension.",
            "type": "object",
            "properties": {
                "instanceName": {
                    "description": "The name of the newly created instance",
                    "type": "string"
                }
            }
        },
        "restAPI.ExtensionsResponse": {
            "description": "Response containing all available extensions",
            "type": "object",
            "properties": {
                "extensions": {
                    "description": "All available extensions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restAPI.ExtensionsResponseExtension"
                    }
                }
            }
        },
        "restAPI.ExtensionsResponseExtension": {
            "description": "Extension information",
            "type": "object",
            "properties": {
                "description": {
                    "description": "The description of the extension to be displayed to the user.",
                    "type": "string"
                },
                "id": {
                    "description": "ID of the extension. Don't store this as it may change in the future.",
                    "type": "string"
                },
                "installableVersions": {
                    "description": "A list of versions of this extension available for installation.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "The name of the extension to be displayed to the user.",
                    "type": "string"
                }
            }
        },
        "restAPI.InstallationsResponse": {
            "type": "object",
            "properties": {
                "installations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restAPI.InstallationsResponseInstallation"
                    }
                }
            }
        },
        "restAPI.InstallationsResponseInstallation": {
            "type": "object",
            "properties": {
                "instanceParameters": {
                    "type": "array",
                    "items": {}
                },
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "restAPI.ParameterValue": {
            "description": "Parameter values for creating a new instance.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the parameter",
                    "type": "string"
                },
                "value": {
                    "description": "The value of the parameter",
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "List, install and uninstall extensions",
            "name": "extension"
        },
        {
            "description": "List, create and remove instances of an extension",
            "name": "instance"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Exasol extension manager REST API",
	Description:      "This is a REST API for managing extensions like virtual schemas in an Exasol database.\n\nIt allows you to install a new extension and create multiple instances for it.\n\nAuthentication is done by passing database connection parameters host, port and credentials via URL parameters. Credentials can be either:\n- Username and password (parameters `dbUser` and `dbPassword`)\n- Access token (parameter `dbAccessToken`)\n- Refresh token (parameter `dbRefreshToken`)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
