basePath: /
consumes:
- application/json
definitions:
  restAPI.CreateInstanceRequest:
    description: Request data for creating a new instance of an extension.
    properties:
      extensionId:
        description: The ID of the extension
        type: string
      extensionVersion:
        description: The version of the extension
        type: string
      parameterValues:
        description: The parameters for the new instance
        items:
          $ref: '#/definitions/restAPI.ParameterValue'
        type: array
    type: object
  restAPI.CreateInstanceResponse:
    description: Response data for creating a new instance of an extension.
    properties:
      instanceName:
        description: The name of the newly created instance
        type: string
    type: object
  restAPI.ExtensionsResponse:
    description: Response containing all available extensions
    properties:
      extensions:
        description: All available extensions.
        items:
          $ref: '#/definitions/restAPI.ExtensionsResponseExtension'
        type: array
    type: object
  restAPI.ExtensionsResponseExtension:
    description: Extension information
    properties:
      description:
        description: The description of the extension to be displayed to the user.
        type: string
      id:
        description: ID of the extension. Don't store this as it may change in the
          future.
        type: string
      installableVersions:
        description: A list of versions of this extension available for installation.
        items:
          type: string
        type: array
      name:
        description: The name of the extension to be displayed to the user.
        type: string
    type: object
  restAPI.InstallationsResponse:
    properties:
      installations:
        items:
          $ref: '#/definitions/restAPI.InstallationsResponseInstallation'
        type: array
    type: object
  restAPI.InstallationsResponseInstallation:
    properties:
      instanceParameters:
        items: {}
        type: array
      name:
        type: string
      version:
        type: string
    type: object
  restAPI.ParameterValue:
    description: Parameter values for creating a new instance.
    properties:
      name:
        description: The name of the parameter
        type: string
      value:
        description: The value of the parameter
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: opensource@exasol.com
    name: Exasol Integration team
  description: |-
    This is a REST API for managing extensions like virtual schemas in an Exasol database.

    It allows you to install a new extension and create multiple instances for it.

    Authentication is done by passing database connection parameters host, port and credentials via URL parameters. Credentials can be either:
    - Username and password (parameters `dbUser` and `dbPassword`)
    - Access token (parameter `dbAccessToken`)
    - Refresh token (parameter `dbRefreshToken`)
  license:
    name: MIT
    url: https://github.com/exasol/extension-manager/blob/main/LICENSE
  title: Exasol extension manager REST API
  version: 0.1.0
paths:
  /extensions:
    get:
      description: Get a list of all available extensions, i.e. extensions that can
        be installed.
      operationId: getAvailableExtensions
      parameters:
      - description: Hostname of the Exasol DB to manage
        in: query
        name: dbHost
        required: true
        type: string
      - description: Port number of the Exasol DB to manage
        in: query
        name: dbPort
        required: true
        type: integer
      - description: Username of the Exasol DB to manage
        in: query
        name: dbUser
        type: string
      - description: Password of the Exasol DB to manage
        in: query
        name: dbPassword
        type: string
      - description: Access token of the Exasol DB to manage
        in: query
        name: dbAccessToken
        type: string
      - description: Refresh token of the Exasol DB to manage
        in: query
        name: dbRefreshToken
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/restAPI.ExtensionsResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all extensions
      tags:
      - extensions
  /installations:
    get:
      description: Get a list of all installed extensions. Installation means, that
        an extension is installed in the database (e.g. JAR files added to BucketFS
        and Adapter Script created).
      operationId: getInstalledExtensions
      parameters:
      - description: Hostname of the Exasol DB to manage
        in: query
        name: dbHost
        required: true
        type: string
      - description: Port number of the Exasol DB to manage
        in: query
        name: dbPort
        required: true
        type: integer
      - description: Username of the Exasol DB to manage
        in: query
        name: dbUser
        type: string
      - description: Password of the Exasol DB to manage
        in: query
        name: dbPassword
        type: string
      - description: Access token of the Exasol DB to manage
        in: query
        name: dbAccessToken
        type: string
      - description: Refresh token of the Exasol DB to manage
        in: query
        name: dbRefreshToken
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/restAPI.InstallationsResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all installed extensions.
      tags:
      - extensions
    put:
      description: This installs an extension in a given version, e.g. by creating
        Adapter Scripts.
      operationId: installExtension
      parameters:
      - description: Hostname of the Exasol DB to manage
        in: query
        name: dbHost
        required: true
        type: string
      - description: Port number of the Exasol DB to manage
        in: query
        name: dbPort
        required: true
        type: integer
      - description: Username of the Exasol DB to manage
        in: query
        name: dbUser
        type: string
      - description: Password of the Exasol DB to manage
        in: query
        name: dbPassword
        type: string
      - description: Access token of the Exasol DB to manage
        in: query
        name: dbAccessToken
        type: string
      - description: Refresh token of the Exasol DB to manage
        in: query
        name: dbRefreshToken
        type: string
      - description: ID of the extension to install
        in: query
        name: extensionId
        required: true
        type: string
      - description: Version of the extension to install
        in: query
        name: extensionVersion
        required: true
        type: string
      - default: ""
        description: dummy body
        in: body
        name: dummy
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Install an extension.
      tags:
      - extensions
  /instances:
    put:
      description: This creates a new instance of an extension, e.g. a virtual schema.
      operationId: createInstance
      parameters:
      - description: Hostname of the Exasol DB to manage
        in: query
        name: dbHost
        required: true
        type: string
      - description: Port number of the Exasol DB to manage
        in: query
        name: dbPort
        required: true
        type: integer
      - description: Username of the Exasol DB to manage
        in: query
        name: dbUser
        type: string
      - description: Password of the Exasol DB to manage
        in: query
        name: dbPassword
        type: string
      - description: Access token of the Exasol DB to manage
        in: query
        name: dbAccessToken
        type: string
      - description: Refresh token of the Exasol DB to manage
        in: query
        name: dbRefreshToken
        type: string
      - description: Request data for creating an instance
        in: body
        name: createInstanceRequest
        required: true
        schema:
          $ref: '#/definitions/restAPI.CreateInstanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/restAPI.CreateInstanceResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create an instance of an extension.
      tags:
      - instances
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
tags:
- description: List, install and uninstall extensions
  name: extensions
- description: List, create and remove instances of an extension
  name: instances
