name: CI Build Parameter Validator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: extension-parameter-validator/package-lock.json
      - name: Install dependencies
        run: |
          cd extension-parameter-validator/
          npm ci
      - name: Run tests
        run: |
          cd extension-parameter-validator/
          npm test
      - name: Run build
        run: |
          cd extension-parameter-validator/
          npm run build