name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-

      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"

      - name: Install dependencies
        run: |
          go get -t ./...

      - name: Check generated code
        run: |
          go generate ./...
          if [[ `git status --porcelain` ]]; then
            echo "Project files did change:\n"
            git --no-pager diff
            exit 1
          fi

      - name: golangci-lint
        run: |
          ./ci/install_and_run_golangci-lint.sh

      - name: Build
        run: |
          go build ./...
          go build -o extension-manager cmd/main.go

      - name: Unit tests
        run: |
          go test -v -p 1 -count 1 -short ./...

      - name: Integration tests
        run: |
          # -p 1 tells go not to run the tests in parallel. See the developers_guide.
          go test -v -p 1 -count 1 -coverprofile=coverage.out ./...

      - name: Build and test integration test framework
        run: cd ./extension-manager-integration-test-java/testing-extension && npm ci

      - name: Build and test integration test framework
        run: mvn --batch-mode clean verify --file pom.xml -DtrimStackTrace=false

      - name: Prepare SonarCloud scan
        # Without this step, Sonar will fail with this error:
        # Maven project detected. You should run the goal 'org.sonarsource.scanner.maven:sonar' during build rather than using this GitHub Action."
        run: rm ./pom.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: extension-manager binary
          path: extension-manager
          if-no-files-found: error
          retention-days: 5
