name: Backend CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go get -t ./...

      - name: Check generated code
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go generate
          if [[ `git status --porcelain` ]]; then
            exit 1
          fi
          
      - name: golangci-lint
        run: |
          ./ci/install_and_run_golangci-lint.sh

      - name: Unit tests
        run: |
          go test -v -short ./...

      - name: Integration tests
        run: |
          # -p 1 tells go not to run the tests in parallel. See the developers_guide.
          go test -v -p 1 -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
