name: CI Build next Java

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  java-17-compatibility:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
        id: go
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode --update-snapshots clean package -DtrimStackTrace=false -Djava.version=17
