name: Report Security Issues for Repository

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 2 * * *"

jobs:
  report_security_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: |
            11
            17
          cache: "maven"
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Install to local maven repo
        # This avoids this error:
        # [ERROR] Failed to execute goal on project extension-manager-integration-test-java: Could not resolve dependencies for project com.exasol:extension-manager-integration-test-java:jar:0.2.3: Could not find artifact com.exasol:extension-manager-client-java:jar:0.2.3 in central
        run: mvn --batch-mode install -DskipTests

      - name: Generate ossindex report
        run: |
          mvn org.sonatype.ossindex.maven:ossindex-maven-plugin:audit \
              org.sonatype.ossindex.maven:ossindex-maven-plugin:audit-aggregate

      - name: Check for Go vulnerabilities
        if: always()
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -version
          govulncheck -format text -mode source -scan symbol -show verbose -test ./...

      - name: Check registry for NPM vulnerabilities
        if: always()
        run: cd registry && npm audit --audit-level=high # Suppress warning about unfixable vulnerability https://github.com/advisories/GHSA-f886-m6hf-6m8v (requires an update of aws-cdk-lib)
      - name: Check registry-upload for NPM vulnerabilities
        if: always()
        run: cd registry-upload && npm audit
      - name: Check parameterValidator for NPM vulnerabilities
        if: always()
        run: cd pkg/parameterValidator && npm audit
      - name: Check testing-extension for NPM vulnerabilities
        if: always()
        run: cd extension-manager-integration-test-java/testing-extension && npm audit
