name: Interface CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ gibucketFsUploadsthub.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: cd interface && npm install
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install and configure
        run: |
          cd interface && npm run build
