name: Release Droid - Prepare Original Checksum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            11
            17
          cache: "maven"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
        id: go

      - name: Prepare testing extension
        run: cd ./extension-manager-integration-test-java/testing-extension && npm ci

      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Run tests and build with Maven
        run: mvn --batch-mode clean verify --file pom.xml
      - name: Prepare checksum
        run: find ./*/target -maxdepth 1 -name "*.jar" -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v4
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum
